In [1]:
#comente
#Importa as bibliotecas numpy e tensorflow, chamando cada biblioteca com um alias
#numpy é uma biblioteca para realização de cálculos, trabalhar com vetores, matrizes e arranjos de forma #comparável ao do matlab
#tensorflow é uma biblioteca desenvolvida pelo google para inteligência artificial
import numpy as np
import tensorflow as tf

In [2]:
#comente
#abre uma variável sess, associando a ela a classe sessão do tensorflow, que encapsula objetos em um ambiente na qual os objetos serão executados.
#Instanciação de uma classe Sessão do tensorflow
#https://www.tensorflow.org/api_docs/python/tf/constant
sess = tf.Session()

In [3]:
#comente
#Declaração de uma função chamada print_tf, cuja função é informar o tipo do parâmetro passado e seu valor, logo em seguida. 
def print_tf(x):
    print("TIPO: \n %s" % (type(x)))
    print("Valor: \n %s" % (x))

In [4]:
#comente
#a variável hello recebe uma função que define uma constante do tensorflow (constante tensor), com o valor informado entre #parentesis; a funcao print_tf foi definida acima vai informar o tipo da variavel hello e seu tipo.
hello = tf.constant("www.deeplearningbrasil.com.br")
print_tf(hello)

TIPO: 
 <class 'tensorflow.python.framework.ops.Tensor'>
Valor: 
 Tensor("Const:0", shape=(), dtype=string)


In [5]:
#comente
#Run é um método da classe session, cuja função é executar os objetos que foram definidos dentro da seção. Ele serve para rodar as operações existentes e montar os grafos, que é como o tensorflow funciona. Depois essa variável hello_out é impressa com a função definida anteriormente.
hello_out = sess.run(hello)
print_tf(hello_out)

TIPO: 
 <class 'bytes'>
Valor: 
 b'www.deeplearningbrasil.com.br'


In [6]:
#comente
#variável a define a constante tensorflow com valor 1,5
#variavel b é definido com a constante tensorflow com o valor 2,5
#A funcao em seguida imprime o tipo e valor das variáveis a e b
a = tf.constant(1.5)
b = tf.constant(2.5)
print_tf(a)
print_tf(b)

TIPO: 
 <class 'tensorflow.python.framework.ops.Tensor'>
Valor: 
 Tensor("Const_1:0", shape=(), dtype=float32)
TIPO: 
 <class 'tensorflow.python.framework.ops.Tensor'>
Valor: 
 Tensor("Const_2:0", shape=(), dtype=float32)


In [7]:
#comente
#São realizadas as operações de inicialização dos grafos na qual foi definido para as constantes tensor a e #b, para as variáveis a_out e b_out; depois a função que mostra o tipo das variáveis e valores é executada
a_out = sess.run(a)
b_out = sess.run(b)
print_tf(a_out)
print_tf(b_out)

TIPO: 
 <class 'numpy.float32'>
Valor: 
 1.5
TIPO: 
 <class 'numpy.float32'>
Valor: 
 2.5


In [8]:
#comente
#Funcao soma do tensorflow na qual é realizada a adição das constantes tensor a e b e o resultado é #colocado na variavel a_plus_b; depois a função definida anteriormente define o tipo e o valor dessa #variavel a_plus_b
a_plus_b = tf.add(a, b)
print_tf(a_plus_b)

TIPO: 
 <class 'tensorflow.python.framework.ops.Tensor'>
Valor: 
 Tensor("Add:0", shape=(), dtype=float32)


In [9]:
#comente
#Executa as operações do tensor definido a_plus_b, inicializa o grafo dessa variavel a_plus_b, entregando o resultado na variável (a_plus_b_out); novamente é chamada a função print_tf.
a_plus_b_out = sess.run(a_plus_b)
print_tf(a_plus_b_out)

TIPO: 
 <class 'numpy.float32'>
Valor: 
 4.0


In [10]:
#comente
#Não existe mais a funcao mul no tensorflow; ela foi substituída por multiply, que deve ser corrigida abaixo.
#Executa a multiplicacao das constantes tensor a e b; depois é executado através da constante run; depois a função print_tf é chamada para apresentar tipo e valor da variável a_mul_b_out.
a_mul_b = tf.multiply(a, b)
a_mul_b_out = sess.run(a_mul_b)
print_tf(a_mul_b_out)

TIPO: 
 <class 'numpy.float32'>
Valor: 
 3.75


In [11]:
#comente
#Método para criar uma criar uma variável tensor, só que ela precisa obrigatoriamente ser inicializada com um valor de tensor de qualquer valor, neste caso foi definido que o shape é uma curva gaussiana (curva normal) cujos valores aleatórios serão baseados numa matriz 5 por 2; quanto mais próximo do pico da gaussiana, haverá uma certa distribuição de probabilidades, não encontrada nas extremidades. ; cujo desvio padrão foi definido por stddev = 0,1. 
weight = tf.Variable(tf.random_normal([5, 2], stddev=0.1))
print_tf(weight)

TIPO: 
 <class 'tensorflow.python.ops.variables.Variable'>
Valor: 
 <tf.Variable 'Variable:0' shape=(5, 2) dtype=float32_ref>


In [12]:
#comente - acontecerá um erro aqui
#Executa o tensor definido pela variável weight
#Faltou a inicialização da variável weight_out, que está sendo feito no próximo conjunto de código
#esse trecho foi comentado, para que não haja mais erro.
weight_out = sess.run(weight)
print_tf(weight_out)

FailedPreconditionError: Attempting to use uninitialized value Variable
	 [[Node: _retval_Variable_0_0 = _Retval[T=DT_FLOAT, index=0, _device="/job:localhost/replica:0/task:0/cpu:0"](Variable)]]

In [13]:
#comente - acontecerá um erro aqui
#Executa o tensor definido pela variável weight
#Faltou a inicialização da variável weight_out, que está sendo feito no próximo conjunto de código
#esse trecho foi comentado, para que não haja mais erro.
#weight_out = sess.run(weight)
#print_tf(weight_out)

In [14]:
#comente
#Inicializa todas as variáveis tensors definidas no código, que no caso é só a weight. 
#Desta forma é possível executar a variável weight.
init = tf.initialize_all_variables()
sess.run(init)

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [15]:
#comente
#A sessão é executada associada à variável weight. A funcao print_tf é chamada, imprimindo tipo e valor de weight, depois é apresentado em tela a string "INITIALIZING ALL VARIABLES"
weight_out = sess.run(weight)
print_tf(weight_out)
print ("INITIALIZING ALL VARIABLES")

TIPO: 
 <class 'numpy.ndarray'>
Valor: 
 [[-0.1599749  -0.01970405]
 [-0.10489478  0.03872173]
 [-0.20562278  0.15155455]
 [ 0.06286802  0.09530853]
 [-0.09910833  0.05111244]]
INITIALIZING ALL VARIABLES


In [17]:
#comente
#Cria um ambiente para receber o que está sendo feito; as variáveis e constantes tensors que serão usados dentro do ambiente placeholder criado e o resultado será gerado. O tipo dos tensors recebidos serão do tipo float. O shape do resultado é a matriz [None, 5].
x = tf.placeholder(tf.float32, [None, 5])
print_tf(x)

TIPO: 
 <class 'tensorflow.python.framework.ops.Tensor'>
Valor: 
 Tensor("Placeholder_1:0", shape=(?, 5), dtype=float32)


In [18]:
#comente
#Funcao do tensorflow de multiplicacao de matrizes, placeholder pelos pesos.
oper = tf.matmul(x, weight)
print_tf(oper)

TIPO: 
 <class 'tensorflow.python.framework.ops.Tensor'>
Valor: 
 Tensor("MatMul:0", shape=(?, 2), dtype=float32)


In [19]:
#comente
#Data recebe um vetor de tamanho 1 x 5 que terá valores aleatórios criados pela funcao random.rand #(biblioteca do numpy); depois a sessão é executada, com a diferença de que é realimentada com os valores aleatórios de data
data = np.random.rand(1, 5)
oper_out = sess.run(oper, feed_dict={x: data})
print_tf(oper_out)

TIPO: 
 <class 'numpy.ndarray'>
Valor: 
 [[-0.16172059  0.12191164]]


In [20]:
#comente
#Tudo é feito novamente, com a diferença de a realimentação é com uma matriz de duas dimensões.
data = np.random.rand(2, 5)
oper_out = sess.run(oper, feed_dict={x: data})
print_tf(oper_out)

TIPO: 
 <class 'numpy.ndarray'>
Valor: 
 [[-0.22922245  0.08486627]
 [-0.25312066  0.07974741]]
